### ISSUE TITLE
Schnittstelle zur Datenbank

### ISSUE THREAD

**Issue by giangkute7v** [bp-group-60/Hybrider-Passwortmanager#10]
### Beschreibung:
Als Entwickler*in brauche ich eine Schnittstelle von Java zur Datenbank, mit der ich die Informationen von der Datenbank abfragen und verwalten kann.

### Akzeptanzkriterium:
Schnittstelle zur Datenbank vorhanden. Man kann in Java die Abfrage erstellen, die Antwort bekommen und die Datenbank verwalten, modifizieren.

**Comment by vadim-spiro** [comment]
Erste triviale Schnittstellen/abfragen sind in PasswordDao.java.

**Comment by T3Cabon** [comment]
Code Review 2-5 in Google Drive
