### ISSUE TITLE
Datenbankdesign

### ISSUE THREAD

**Issue by giangkute7v** [bp-group-60/Hybrider-Passwortmanager#11]
### Beschreibung:
Als Entwickler*in brauche ich eine Datenbank für die Speicherung von sensible Informationen von dem App.

### Akzeptanzkriterium:
Die Datenbank ist in 3. Normalform und ist geeignet für die Speicherung von Passwörter und die dazugehörige Nutzername, app, sowie Masterkonto

**Comment by vadim-spiro** [comment]
Grundfunktionen sind fertig, für weitere Funktionalität kann die Datenbank später erweitert werden.

**Comment by T3Cabon** [comment]
Code-Review 2-5 in Google Drive
