### ISSUE TITLE
Schnittstelle von Javascript und Java

### ISSUE THREAD

**Issue by giangkute7v** [bp-group-60/Hybrider-Passwortmanager#9]
### Beschreibung:
Als Entwickler*in brauche ich eine Schnittstelle zwischen Java und Javascript, damit Javascript Methoden in Java aufrufen kann.

### Akzeptanzkriterium:
Die Methoden von Javascript und Java interagieren untereinander einwandfrei.

**Comment by vadim-spiro** [comment]
Es werden die Methoden in Java direkt geschrieben und können anschließend in javascript verwendet werden.

**Comment by vadim-spiro** [comment]
Daher müssen wir die Klasse JavascriptHandler direkt mit der gewünschten Funktionalität erweitern.

**Comment by T3Cabon** [comment]
Code-Review in Google Drive
